name: GitHub API Usage Tracker
description: Track GitHub API rate-limit usage for a job (core/graphql/search)
author: Really Him
branding:
  icon: activity
  color: blue

inputs:
  token:
    description: Token to query rate_limit (defaults to github.token)
    required: false
    default: ${{ github.token }}
  quiet:
    description: Suppress intermediate logs when true
    required: false
    default: "false"
  buckets:
    description: Comma-separated rate-limit buckets to track (core,search,graphql,code_search,integration_manifest,dependency_snapshots,dependency_sbom,code_scanning_upload,actions_runner_registration,source_import)
    required: false
    default: core,search,graphql
  output_path:
    description: Path to write JSON report; leave empty to skip
    required: false
    default: ""

outputs:
  usage:
    description: JSON string of used requests per bucket (core/graphql/search)

runs:
  using: node20
  pre: dist/pre/index.js
  main: dist/noop/index.js
  post: dist/post/index.js
